### ISSUE TITLE
CRAN release with other algos (skmeans, kmedoids etc)

### ISSUE THREAD

**Issue by talegari** [flashxio/knorR#8]
Hi,

Thanks for these really fast implementations! When do you plan for the CRAN release with algorithms other than kmeans? (I am planning to release a package on CRAN importing knor).

**Comment by disa-mhembere** [comment]
Hello,

The clusternor package contains these algorithms already: https://cran.r-project.org/web/packages/clusternor/index.html. You can import that instead.

**Comment by talegari** [comment]
Thanks, my bad!
